{{- if .Values.clusterRoleBindings }}
{{- $root := . }}
{{- range $name, $rolebinding := .Values.clusterRoleBindings }}
{{- if not $rolebinding.disabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
roleRef:
 kind: ClusterRole
 name: {{ $rolebinding.roleName }}
 apiGroup: {{ $rolebinding.apiGroup | default "rbac.authorization.k8s.io" }}
{{- if $rolebinding.subjects }}
subjects:
{{ toYaml $rolebinding.subjects | indent 0 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
